## Here we are categoring the netflix type on the basic of the description|

In [8]:
import pandas as pd 
import numpy as np

In [2]:
netflix_data = pd.read_csv('netflix_titles.csv')
netflix_data.head()

show_id     type                                    title  \
0  81145628    Movie  Norm of the North: King Sized Adventure   
1  80117401    Movie               Jandino: Whatever it Takes   
2  70234439  TV Show                       Transformers Prime   
3  80058654  TV Show         Transformers: Robots in Disguise   
4  80125979    Movie                             #realityhigh   

                   director  \
0  Richard Finn, Tim Maltby   
1                       NaN   
2                       NaN   
3                       NaN   
4          Fernando Lebrija   

                                                cast  \
0  Alan Marriott, Andrew Toth, Brian Dobson, Cole...   
1                                   Jandino Asporaat   
2  Peter Cullen, Sumalee Montano, Frank Welker, J...   
3  Will Friedle, Darren Criss, Constance Zimmer, ...   
4  Nesta Cooper, Kate Walsh, John Michael Higgins...   

                                    country         date_added  release_year  \
0  United States, India, South Korea, China  September 9, 2019          2019   
1                            United Kingdom  September 9, 2016          2016   
2                             United States  September 8, 2018          2013   
3                             United States  September 8, 2018          2016   
4                             United States  September 8, 2017          2017   

     rating  duration                           listed_in  \
0     TV-PG    90 min  Children & Family Movies, Comedies   
1     TV-MA    94 min                     Stand-Up Comedy   
2  TV-Y7-FV  1 Season                            Kids' TV   
3     TV-Y7  1 Season                            Kids' TV   
4     TV-14    99 min                            Comedies   

                                         description  
0  Before planning an awesome wedding for his gra...  
1  Jandino Asporaat riffs on the challenges of ra...  
2  With the help of three human allies, the Autob...  
3  When a prison ship crash unleashes hundreds of...  
4  When nerdy high schooler Dani finally attracts...

In [3]:
# To check the desciption is nan or not
netflix_data['description'].isna().sum()

0

In [5]:
# To check dtype of the description
netflix_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6234 entries, 0 to 6233
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   show_id       6234 non-null   int64 
 1   type          6234 non-null   object
 2   title         6234 non-null   object
 3   director      4265 non-null   object
 4   cast          5664 non-null   object
 5   country       5758 non-null   object
 6   date_added    6223 non-null   object
 7   release_year  6234 non-null   int64 
 8   rating        6224 non-null   object
 9   duration      6234 non-null   object
 10  listed_in     6234 non-null   object
 11  description   6234 non-null   object
dtypes: int64(2), object(10)
memory usage: 584.6+ KB


In [9]:
# It is found that the description data is object so changing it to numerical values
# And the type data is also object so changing it into the coresponding numerical values

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

description = le.fit_transform(list(netflix_data['description']))
Type = le.fit_transform(list(netflix_data['type']))

In [10]:
# Showing the description 
description, Type

(array([1903, 3521, 6130, ..., 3856, 4247, 4990]),
 array([0, 0, 1, ..., 0, 1, 1]))

In [11]:
netflix_data.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [24]:
description = description.reshape(-1, 1)

In [25]:
# Split the data for features and labels
X = list(description)
y = list(Type)

In [26]:
# Split the data for training and testing process
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

### Here selecting the model/estimator on the basic of the sklearn cheatsheet

https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

In [83]:
# Using the random forest classifier
from sklearn.neighbors import KNeighborsClassifier
highestAccuracy = 0
for i in range(1, 30, 3):
    model = KNeighborsClassifier(n_neighbors=i)
    model.fit(X_train, y_train)
    accuracy = model.score(X_test, y_test)
    if (accuracy > highestAccuracy):
        highestAccuracy = accuracy
        n = i
print(f"Score:{highestAccuracy} and n_neighbors = {n}")
        
model = KNeighborsClassifier(n_neighbors=n)
model.fit(X_train, y_train)

Score:0.6824378508420208 and n_neighbors = 4


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=4, p=2,
                     weights='uniform')

In [84]:
model.score(X_test, y_test)

0.6824378508420208

In [85]:
prediction = model.predict(X_test)

In [86]:
prediction

array([0, 0, 0, ..., 1, 0, 0])

In [87]:
for i in range(0, 30):
    print(f"Prediction: {'Movie' if prediction[i] == 1 else 'Tv show'} and actual values : {'Movie' if y_test[i] == 1 else 'Tv show'}")

Prediction: Tv show and actual values : Tv show
Prediction: Tv show and actual values : Tv show
Prediction: Tv show and actual values : Tv show
Prediction: Movie and actual values : Movie
Prediction: Tv show and actual values : Tv show
Prediction: Tv show and actual values : Tv show
Prediction: Tv show and actual values : Tv show
Prediction: Tv show and actual values : Tv show
Prediction: Tv show and actual values : Tv show
Prediction: Tv show and actual values : Tv show
Prediction: Tv show and actual values : Tv show
Prediction: Tv show and actual values : Movie
Prediction: Tv show and actual values : Tv show
Prediction: Tv show and actual values : Movie
Prediction: Tv show and actual values : Tv show
Prediction: Tv show and actual values : Tv show
Prediction: Tv show and actual values : Tv show
Prediction: Tv show and actual values : Tv show
Prediction: Tv show and actual values : Tv show
Prediction: Tv show and actual values : Tv show
Prediction: Tv show and actual values : Tv show
